#!/usr/bin/env python3
"""Build the leadership-facing PowerPoint deck from pipeline outputs.

The deck is generated with minimal Office Open XML so the repository stays
self-contained and does not depend on PowerPoint-specific Python libraries.
"""

from __future__ import annotations

import argparse
import html
import json
import zipfile
from pathlib import Path
from typing import Any


SLIDE_W = 13_333_333
SLIDE_H = 7_500_000

COLORS = {
    "ink": "172322",
    "muted": "66716A",
    "paper": "F7F4ED",
    "white": "FFFFFF",
    "teal": "2F6F73",
    "red": "9B4D45",
    "gold": "C48A2C",
    "green": "4F7B58",
    "line": "D8D1C3",
    "dark": "183331",
}


def emu(inches: float) -> int:
    return int(inches * 914400)


def esc(text: Any) -> str:
    return html.escape(str(text), quote=True)


def solid_rect(x: float, y: float, w: float, h: float, fill: str, line: str | None = None, radius: bool = False) -> str:
    geom = "roundRect" if radius else "rect"
    ln = f'<a:ln><a:solidFill><a:srgbClr val="{line}"/></a:solidFill></a:ln>' if line else '<a:ln><a:noFill/></a:ln>'
    return f"""
    <p:sp>
      <p:nvSpPr><p:cNvPr id="1" name="shape"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>
      <p:spPr><a:xfrm><a:off x="{emu(x)}" y="{emu(y)}"/><a:ext cx="{emu(w)}" cy="{emu(h)}"/></a:xfrm><a:prstGeom prst="{geom}"><a:avLst/></a:prstGeom><a:solidFill><a:srgbClr val="{fill}"/></a:solidFill>{ln}</p:spPr>
      <p:txBody><a:bodyPr/><a:lstStyle/><a:p/></p:txBody>
    </p:sp>"""


def text_box(
    text: str,
    x: float,
    y: float,
    w: float,
    h: float,
    size: int = 24,
    color: str = COLORS["ink"],
    bold: bool = False,
    align: str = "l",
) -> str:
    paragraphs = text.split("\n")
    runs = []
    for para in paragraphs:
        bullet = para.startswith("- ")
        body = para[2:] if bullet else para
        mar = ' marL="285750" indent="-171450"' if bullet else ""
        bu = '<a:buChar char="•"/>' if bullet else "<a:buNone/>"
        runs.append(
            f"""<a:p><a:pPr algn="{align}"{mar}>{bu}</a:pPr><a:r><a:rPr lang="en-US" sz="{size*100}"{' b="1"' if bold else ''}><a:solidFill><a:srgbClr val="{color}"/></a:solidFill></a:rPr><a:t>{esc(body)}</a:t></a:r><a:endParaRPr lang="en-US" sz="{size*100}"/></a:p>"""
        )
    return f"""
    <p:sp>
      <p:nvSpPr><p:cNvPr id="2" name="text"/><p:cNvSpPr txBox="1"/><p:nvPr/></p:nvSpPr>
      <p:spPr><a:xfrm><a:off x="{emu(x)}" y="{emu(y)}"/><a:ext cx="{emu(w)}" cy="{emu(h)}"/></a:xfrm><a:prstGeom prst="rect"><a:avLst/></a:prstGeom><a:noFill/><a:ln><a:noFill/></a:ln></p:spPr>
      <p:txBody><a:bodyPr wrap="square" lIns="0" tIns="0" rIns="0" bIns="0"/><a:lstStyle/>{''.join(runs)}</p:txBody>
    </p:sp>"""


def pill(text: str, x: float, y: float, w: float, color: str) -> str:
    return solid_rect(x, y, w, 0.42, color, radius=True) + text_box(text, x + 0.12, y + 0.11, w - 0.24, 0.22, 10, COLORS["white"], True, "ctr")


def title(slide_title: str, kicker: str = "Transcript Intelligence") -> str:
    return (
        text_box(kicker.upper(), 0.55, 0.34, 4.5, 0.28, 10, COLORS["teal"], True)
        + text_box(slide_title, 0.55, 0.72, 11.7, 0.75, 28, COLORS["ink"], True)
    )


def footer() -> str:
    return text_box("Source: 100 provided transcript folders; generated by src/analyze_transcripts.py", 0.55, 7.08, 9, 0.22, 8, COLORS["muted"])


def bar_chart(items: list[tuple[str, float]], x: float, y: float, w: float, h: float, color: str, suffix: str = "") -> str:
    max_v = max([v for _, v in items] or [1])
    row_h = h / max(len(items), 1)
    out = []
    for i, (label, value) in enumerate(items):
        yy = y + i * row_h
        bw = 0.1 if max_v == 0 else (value / max_v) * (w - 2.65)
        out.append(text_box(label, x, yy + 0.06, 2.45, 0.28, 10, COLORS["ink"]))
        out.append(solid_rect(x + 2.55, yy + 0.05, bw, 0.28, color, radius=True))
        out.append(text_box(f"{value:g}{suffix}", x + 2.65 + bw, yy + 0.09, 0.8, 0.2, 9, COLORS["ink"], True))
    return "".join(out)


def metric_card(label: str, value: str, note: str, x: float, y: float, color: str = COLORS["teal"]) -> str:
    return (
        solid_rect(x, y, 3.65, 1.2, COLORS["white"], COLORS["line"], radius=True)
        + text_box(value, x + 0.22, y + 0.2, 1.2, 0.4, 24, color, True)
        + text_box(label, x + 1.35, y + 0.2, 2.0, 0.24, 10, COLORS["muted"], True)
        + text_box(note, x + 1.35, y + 0.5, 2.0, 0.42, 11, COLORS["ink"])
    )


def slide_xml(body: str) -> str:
    return f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:sld xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:cSld><p:bg><p:bgPr><a:solidFill><a:srgbClr val="{COLORS['paper']}"/></a:solidFill><a:effectLst/></p:bgPr></p:bg><p:spTree>
    <p:nvGrpSpPr><p:cNvPr id="0" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>
    <p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/><a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>
    {body}
  </p:spTree></p:cSld><p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr>
</p:sld>"""


def write_pptx(slides: list[str], out: Path) -> None:
    rels = "\n".join(
        f'<Relationship Id="rId{i}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide" Target="slides/slide{i}.xml"/>'
        for i in range(1, len(slides) + 1)
    )
    slide_ids = "\n".join(f'<p:sldId id="{255+i}" r:id="rId{i}"/>' for i in range(1, len(slides) + 1))
    overrides = "\n".join(
        f'<Override PartName="/ppt/slides/slide{i}.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.slide+xml"/>'
        for i in range(1, len(slides) + 1)
    )
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as z:
        z.writestr(
            "[Content_Types].xml",
            f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>
  <Default Extension="xml" ContentType="application/xml"/>
  <Override PartName="/ppt/presentation.xml" ContentType="application/vnd.openxmlformats-officedocument.presentationml.presentation.main+xml"/>
  {overrides}
</Types>""",
        )
        z.writestr(
            "_rels/.rels",
            """<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">
  <Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="ppt/presentation.xml"/>
</Relationships>""",
        )
        z.writestr(
            "ppt/presentation.xml",
            f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<p:presentation xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main">
  <p:sldIdLst>{slide_ids}</p:sldIdLst>
  <p:sldSz cx="{SLIDE_W}" cy="{SLIDE_H}" type="wide"/>
  <p:notesSz cx="6858000" cy="9144000"/>
</p:presentation>""",
        )
        z.writestr(
            "ppt/_rels/presentation.xml.rels",
            f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">{rels}</Relationships>""",
        )
        for i, slide in enumerate(slides, start=1):
            z.writestr(f"ppt/slides/slide{i}.xml", slide_xml(slide))


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--outputs", default="outputs", type=Path)
    parser.add_argument("--deliverables", default="deliverables", type=Path)
    args = parser.parse_args()
    args.deliverables.mkdir(parents=True, exist_ok=True)

    summary = json.loads((args.outputs / "summary_metrics.json").read_text(encoding="utf-8"))
    themes = summary["theme_summary"]
    call_types = summary["call_type_summary"]
    products = summary["product_summary"]
    high_risk = summary["highest_risk_meetings"]

    slides: list[str] = []
    slides.append(
        solid_rect(0, 0, 13.333, 7.5, COLORS["dark"])
        + text_box("Transcript Intelligence", 0.62, 0.62, 8.8, 0.82, 34, COLORS["white"], True)
        + text_box("Turning 100 enterprise call transcripts into theme, sentiment, product-risk, and action signals for leadership.", 0.65, 1.55, 8.8, 0.7, 20, "DCE9E5")
        + pill("Hybrid explainable pipeline", 0.65, 2.55, 2.45, COLORS["teal"])
        + pill("Leadership-ready insights", 3.28, 2.55, 2.35, COLORS["gold"])
        + pill("Reproducible repo", 5.8, 2.55, 1.85, COLORS["green"])
        + metric_card("meetings", "100", "Support, external customer, and internal conversations.", 0.65, 4.35, COLORS["white"])
        + metric_card("themes", "7", "Business-oriented categories for routing and prioritization.", 4.65, 4.35, COLORS["white"])
        + metric_card("highest risk", "10/10", "Reliability and competitive calls repeatedly hit the top risk band.", 8.65, 4.35, COLORS["white"])
    )
    slides.append(
        title("The transcript corpus is an operating signal, not just meeting notes")
        + text_box("- Support calls reveal acute pain: outages, latency, connector bugs, billing disputes.\n- External customer calls reveal commercial risk: renewals, trust, competitive evaluations, roadmap confidence.\n- Internal calls reveal whether the organization is closing the loop on customer pain.", 0.8, 1.8, 6.2, 2.0, 18)
        + metric_card("Customer support", str(next(x["meetings"] for x in call_types if x["call_type"] == "Customer support")), "Highest negative utterance share.", 7.4, 1.7, COLORS["red"])
        + metric_card("External customer", str(next(x["meetings"] for x in call_types if x["call_type"] == "External customer")), "Lower sentiment risk, higher revenue context.", 7.4, 3.05, COLORS["teal"])
        + metric_card("Internal", str(next(x["meetings"] for x in call_types if x["call_type"] == "Internal")), "Prioritization and execution signal.", 7.4, 4.4, COLORS["gold"])
        + footer()
    )
    slides.append(
        title("A transparent hybrid classifier is the right first system")
        + text_box("Pipeline", 0.7, 1.68, 2.1, 0.35, 16, COLORS["teal"], True)
        + text_box("Raw JSON folders -> summaries/topics/key moments -> rule-scored call type, theme, product surface, sentiment, risk -> CSV/JSON/HTML/deck outputs", 0.7, 2.1, 5.4, 1.1, 18)
        + text_box("Why this approach", 0.7, 3.68, 2.8, 0.35, 16, COLORS["teal"], True)
        + text_box("- Explainable enough for product and engineering Q&A.\n- Repeatable with no external services or API keys.\n- Easy to replace theme rules with embeddings or LLM labels later while keeping audit guardrails.", 0.7, 4.08, 5.8, 1.8, 16)
        + solid_rect(7.0, 1.72, 4.7, 3.7, COLORS["white"], COLORS["line"], True)
        + text_box("Core outputs", 7.35, 2.02, 2.4, 0.32, 18, COLORS["ink"], True)
        + text_box("meeting_analysis.csv\nsummary_metrics.json\nanalysis_report.md\ndashboard.html\nTranscript_Intelligence_Leadership_Deck.pptx", 7.35, 2.55, 3.9, 1.8, 16)
        + footer()
    )
    slides.append(
        title("Reliability is the largest and riskiest theme; compliance is broad but healthier")
        + bar_chart([(x["theme"], x["meetings"]) for x in themes], 0.72, 1.65, 7.2, 4.7, COLORS["teal"])
        + text_box("Interpretation", 8.35, 1.8, 3.4, 0.35, 16, COLORS["teal"], True)
        + text_box("Incident & Reliability has fewer meetings than compliance but reaches the risk ceiling because it combines urgent language, customer impact, and technical follow-up. Compliance is frequent, but many conversations are planned reviews or launch/adoption work.", 8.35, 2.25, 3.7, 2.0, 17)
        + footer()
    )
    slides.append(
        title("Sentiment trends separate acute support pain from commercial risk")
        + bar_chart([(x["call_type"], round(x["negative_utterance_share"] * 100, 1)) for x in call_types], 0.75, 1.65, 6.8, 2.4, COLORS["red"], "%")
        + bar_chart([(x["call_type"], x["avg_sentiment_score"]) for x in call_types], 0.75, 4.45, 6.8, 1.7, COLORS["green"])
        + text_box("What it means", 8.2, 1.8, 3.7, 0.35, 16, COLORS["teal"], True)
        + text_box("Support calls are the emotional smoke alarm: 27.1% of utterances are negative. External customer calls sound calmer, but the risk often sits in renewal hesitation, competitive evaluation, and roadmap confidence. Both signals need different owners.", 8.2, 2.25, 3.8, 2.3, 17)
        + footer()
    )
    slides.append(
        title("Product risk concentrates around Detect, then Protect and Identity")
        + bar_chart([(x["product"], x["avg_risk_score"]) for x in products], 0.85, 1.75, 6.6, 3.1, COLORS["gold"])
        + text_box("Recommendation", 8.0, 1.85, 3.7, 0.35, 16, COLORS["teal"], True)
        + text_box("Use transcript intelligence as a product risk router: extract the affected product, evidence quote, account, sentiment, and action owner. Detect should be the first executive dashboard surface because outages, SIEM connectors, alert quality, and competitive gaps recur across call types.", 8.0, 2.3, 3.8, 2.5, 17)
        + footer()
    )
    slides.append(
        title("Highest-risk meetings show the decisions leaders should force")
        + text_box("Meeting", 0.72, 1.62, 5.2, 0.25, 11, COLORS["muted"], True)
        + text_box("Theme", 6.15, 1.62, 2.0, 0.25, 11, COLORS["muted"], True)
        + text_box("Risk", 8.35, 1.62, 0.8, 0.25, 11, COLORS["muted"], True)
        + text_box("Leadership question", 9.35, 1.62, 2.8, 0.25, 11, COLORS["muted"], True)
        + "".join(
            solid_rect(0.65, 1.95 + i * 0.72, 11.7, 0.55, COLORS["white"], COLORS["line"], True)
            + text_box(item["title"][:62], 0.82, 2.1 + i * 0.72, 5.0, 0.22, 10)
            + text_box(item["theme"], 6.15, 2.1 + i * 0.72, 1.9, 0.22, 10)
            + text_box(str(item["risk_score"]), 8.45, 2.1 + i * 0.72, 0.4, 0.22, 11, COLORS["red"], True)
            + text_box("Owner, tradeoff, customer impact", 9.35, 2.1 + i * 0.72, 2.7, 0.22, 10)
            for i, item in enumerate(high_risk[:6])
        )
        + footer()
    )
    slides.append(
        title("Three insight products would make this valuable beyond analysis")
        + metric_card("Sales / CS", "1", "Revenue risk heatmap: renewal language + competitor mentions + negative sentiment.", 0.75, 1.8, COLORS["teal"])
        + metric_card("Product", "2", "Product gap backlog: repeated pain points with quotes, accounts, and urgency.", 4.85, 1.8, COLORS["gold"])
        + metric_card("Engineering", "3", "Incident learning loop: connect support pain to post-incident and sprint-planning follow-through.", 8.95, 1.8, COLORS["green"])
        + text_box("These are stakeholder workflows, not charts. The product should help each leader decide what to do next and where to look for evidence.", 1.0, 4.2, 10.8, 0.9, 22, COLORS["ink"], True, "ctr")
        + footer()
    )
    slides.append(
        title("Recommended next build")
        + text_box("- Ship a theme and risk dashboard for Detect reliability first.\n- Add account-level revenue risk overlays for renewal and competitive calls.\n- Add owner extraction so action items become trackable workflow, not static notes.\n- Upgrade classifier with embeddings or LLM labels, keeping the rule layer as explainable QA.", 0.9, 1.85, 6.4, 2.4, 18)
        + solid_rect(8.0, 1.8, 3.6, 3.4, COLORS["white"], COLORS["line"], True)
        + text_box("Demo path", 8.35, 2.1, 2.2, 0.3, 18, COLORS["ink"], True)
        + text_box("1. Run src/analyze_transcripts.py\n2. Open outputs/dashboard.html\n3. Review analysis_report.md\n4. Walk through this deck\n5. Show highest-risk CSV rows", 8.35, 2.65, 2.8, 1.7, 15)
        + footer()
    )

    write_pptx(slides, args.deliverables / "Transcript_Intelligence_Leadership_Deck.pptx")
    print(args.deliverables / "Transcript_Intelligence_Leadership_Deck.pptx")


if __name__ == "__main__":
    main()
