#!/usr/bin/env node
const fs = require("fs");
const path = require("path");
const pptxgen = require("pptxgenjs");

const outputsDir = process.argv.includes("--outputs")
  ? process.argv[process.argv.indexOf("--outputs") + 1]
  : "outputs";
const deliverablesDir = process.argv.includes("--deliverables")
  ? process.argv[process.argv.indexOf("--deliverables") + 1]
  : "deliverables";

const summary = JSON.parse(fs.readFileSync(path.join(outputsDir, "summary_metrics.json"), "utf8"));
const clusterSummaryPath = path.join(outputsDir, "cluster_summary.json");
const clusterSummary = fs.existsSync(clusterSummaryPath)
  ? JSON.parse(fs.readFileSync(clusterSummaryPath, "utf8"))
  : [];
const evaluationPath = path.join(outputsDir, "evaluation_metrics.json");
const evaluation = fs.existsSync(evaluationPath)
  ? JSON.parse(fs.readFileSync(evaluationPath, "utf8"))
  : { avg_theme_confidence: 0, avg_cluster_purity: 0, low_confidence_meetings: 0, low_confidence_share: 0 };
const goldEvaluationPath = path.join(outputsDir, "gold_label_evaluation.json");
const goldEvaluation = fs.existsSync(goldEvaluationPath)
  ? JSON.parse(fs.readFileSync(goldEvaluationPath, "utf8"))
  : { call_type_accuracy: 0, theme_accuracy: 0, risk_accuracy: 0, high_risk_detection: { f1: 0 } };
fs.mkdirSync(deliverablesDir, { recursive: true });

const pptx = new pptxgen();
pptx.layout = "LAYOUT_WIDE";
pptx.author = "Srikaveri";
pptx.subject = "Transcript Intelligence Take-Home";
pptx.title = "Transcript Intelligence Leadership Deck";
pptx.company = "AegisCloud assessment";
pptx.lang = "en-US";
pptx.theme = {
  headFontFace: "Aptos Display",
  bodyFontFace: "Aptos",
  lang: "en-US",
};
pptx.defineLayout({ name: "CUSTOM_WIDE", width: 13.333, height: 7.5 });
pptx.layout = "CUSTOM_WIDE";
pptx.margin = 0;

const C = {
  ink: "172322",
  muted: "66716A",
  paper: "F7F4ED",
  white: "FFFFFF",
  teal: "2F6F73",
  red: "9B4D45",
  gold: "C48A2C",
  green: "4F7B58",
  line: "D8D1C3",
  dark: "183331",
};

function addBg(slide, color = C.paper) {
  slide.background = { color };
}

function title(slide, text, kicker = "Transcript Intelligence") {
  slide.addText(kicker.toUpperCase(), {
    x: 0.55,
    y: 0.32,
    w: 4.5,
    h: 0.28,
    fontFace: "Aptos",
    fontSize: 9,
    bold: true,
    color: C.teal,
    breakLine: false,
  });
  slide.addText(text, {
    x: 0.55,
    y: 0.7,
    w: 11.8,
    h: 0.75,
    fontFace: "Aptos Display",
    fontSize: 28,
    bold: true,
    color: C.ink,
    margin: 0,
    fit: "shrink",
  });
}

function footer(slide) {
  slide.addText("Source: 100 provided transcript folders; generated by src/analyze_transcripts.py", {
    x: 0.55,
    y: 7.08,
    w: 9.5,
    h: 0.18,
    fontSize: 7,
    color: C.muted,
    margin: 0,
  });
}

function rect(slide, x, y, w, h, fill, line = fill, radius = 0.08) {
  slide.addShape(pptx.ShapeType.roundRect, {
    x,
    y,
    w,
    h,
    rectRadius: radius,
    fill: { color: fill },
    line: { color: line, transparency: line === fill ? 100 : 0, width: 1 },
  });
}

function card(slide, label, value, note, x, y, color = C.teal) {
  rect(slide, x, y, 3.65, 1.15, C.white, C.line);
  slide.addText(value, { x: x + 0.22, y: y + 0.18, w: 1.1, h: 0.38, fontSize: 24, bold: true, color, margin: 0, fit: "shrink" });
  slide.addText(label, { x: x + 1.32, y: y + 0.18, w: 2.0, h: 0.2, fontSize: 9, bold: true, color: C.muted, margin: 0, fit: "shrink" });
  slide.addText(note, { x: x + 1.32, y: y + 0.48, w: 2.0, h: 0.45, fontSize: 11, color: C.ink, margin: 0.02, fit: "shrink" });
}

function pill(slide, text, x, y, w, color) {
  rect(slide, x, y, w, 0.42, color, color);
  slide.addText(text, { x: x + 0.1, y: y + 0.1, w: w - 0.2, h: 0.2, fontSize: 9, bold: true, color: C.white, align: "center", margin: 0, fit: "shrink" });
}

function bullets(slide, items, x, y, w, h, fontSize = 17) {
  slide.addText(
    items.map((t) => ({ text: t, options: { bullet: { type: "ul" }, hanging: 4 } })),
    { x, y, w, h, fontSize, color: C.ink, breakLine: false, margin: 0.04, fit: "shrink", paraSpaceAfterPt: 8 }
  );
}

function barChart(slide, items, x, y, w, h, color, suffix = "") {
  const max = Math.max(...items.map(([, v]) => v), 1);
  const rowH = h / items.length;
  items.forEach(([label, value], i) => {
    const yy = y + i * rowH;
    const barW = Math.max(0.05, (value / max) * (w - 2.75));
    slide.addText(label, { x, y: yy + 0.04, w: 2.5, h: 0.22, fontSize: 9.5, color: C.ink, margin: 0, fit: "shrink" });
    rect(slide, x + 2.6, yy + 0.04, barW, 0.28, color, color);
    slide.addText(`${value}${suffix}`, { x: x + 2.72 + barW, y: yy + 0.08, w: 0.65, h: 0.18, fontSize: 8.5, bold: true, color: C.ink, margin: 0, fit: "shrink" });
  });
}

function note(slide, heading, text, x, y, w, h) {
  slide.addText(heading, { x, y, w, h: 0.28, fontSize: 15, bold: true, color: C.teal, margin: 0 });
  slide.addText(text, { x, y: y + 0.42, w, h: h - 0.42, fontSize: 16, color: C.ink, margin: 0.02, fit: "shrink", breakLine: false });
}

function getType(name) {
  return summary.call_type_summary.find((x) => x.call_type === name);
}

// Slide 1
{
  const s = pptx.addSlide();
  addBg(s, C.dark);
  s.addText("Transcript Intelligence", { x: 0.62, y: 0.62, w: 8.8, h: 0.7, fontFace: "Aptos Display", fontSize: 34, bold: true, color: C.white, margin: 0 });
  s.addText("Turning 100 enterprise call transcripts into theme, sentiment, product-risk, and action signals for leadership.", { x: 0.65, y: 1.55, w: 8.9, h: 0.65, fontSize: 20, color: "DCE9E5", margin: 0, fit: "shrink" });
  pill(s, "Hybrid explainable pipeline", 0.65, 2.55, 2.45, C.teal);
  pill(s, "Leadership-ready insights", 3.28, 2.55, 2.35, C.gold);
  pill(s, "Reproducible repo", 5.8, 2.55, 1.85, C.green);
  card(s, "meetings", "100", "Support, external customer, and internal conversations.", 0.65, 4.35, C.white);
  card(s, "themes", "7", "Business-oriented categories for routing and prioritization.", 4.65, 4.35, C.white);
  card(s, "highest risk", "10/10", "Reliability and competitive calls repeatedly hit the top risk band.", 8.65, 4.35, C.white);
}

// Slide 2
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "The transcript corpus is an operating signal, not just meeting notes");
  bullets(s, [
    "Support calls reveal acute pain: outages, latency, connector bugs, billing disputes.",
    "External customer calls reveal commercial risk: renewals, trust, competitive evaluations, roadmap confidence.",
    "Internal calls reveal whether the organization is closing the loop on customer pain.",
  ], 0.8, 1.82, 6.2, 2.0, 18);
  card(s, "Customer support", String(getType("Customer support").meetings), "Highest negative utterance share.", 7.4, 1.7, C.red);
  card(s, "External customer", String(getType("External customer").meetings), "Lower sentiment risk, higher revenue context.", 7.4, 3.05, C.teal);
  card(s, "Internal", String(getType("Internal").meetings), "Prioritization and execution signal.", 7.4, 4.4, C.gold);
  footer(s);
}

// Slide 3
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "A transparent hybrid classifier is the right first system");
  note(s, "Pipeline", "Raw JSON folders -> summaries/topics/key moments -> rule-scored call type, theme, product surface, sentiment, risk -> CSV/JSON/HTML/deck outputs", 0.7, 1.68, 5.7, 1.45);
  bullets(s, [
    "Explainable enough for product and engineering Q&A.",
    "Repeatable with no external services or API keys.",
    "Easy to replace theme rules with embeddings or LLM labels later while keeping audit guardrails.",
  ], 0.7, 3.68, 5.9, 1.7, 16);
  rect(s, 7.0, 1.72, 4.7, 3.7, C.white, C.line);
  s.addText("Core outputs", { x: 7.35, y: 2.02, w: 2.4, h: 0.32, fontSize: 18, bold: true, color: C.ink, margin: 0 });
  s.addText("meeting_analysis.csv\nsummary_metrics.json\nanalysis_report.md\ndashboard.html\nTranscript_Intelligence_Leadership_Deck.pptx", { x: 7.35, y: 2.55, w: 3.9, h: 1.8, fontSize: 15, color: C.ink, margin: 0, fit: "shrink" });
  footer(s);
}

// Slide 4
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "Reliability is the largest high-risk signal; compliance is broad but healthier");
  barChart(s, summary.theme_summary.map((x) => [x.theme, x.meetings]), 0.72, 1.65, 7.2, 4.7, C.teal);
  note(s, "Interpretation", "Incident & Reliability reaches the risk ceiling because it combines urgent language, customer impact, and technical follow-up. Compliance is frequent, but many conversations are planned reviews or launch/adoption work.", 8.35, 1.8, 3.65, 2.4);
  footer(s);
}

// Slide 5
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "Sentiment trends separate acute support pain from commercial risk");
  barChart(s, summary.call_type_summary.map((x) => [x.call_type, Number((x.negative_utterance_share * 100).toFixed(1))]), 0.75, 1.65, 6.8, 2.4, C.red, "%");
  barChart(s, summary.call_type_summary.map((x) => [x.call_type, x.avg_sentiment_score]), 0.75, 4.45, 6.8, 1.7, C.green);
  note(s, "What it means", "Support calls are the emotional smoke alarm: 27.1% of utterances are negative. External customer calls sound calmer, but risk often sits in renewal hesitation, competitive evaluation, and roadmap confidence. Both signals need different owners.", 8.2, 1.8, 3.8, 2.5);
  footer(s);
}

// Slide 6
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "Product risk concentrates around Detect, then Protect and Identity");
  barChart(s, summary.product_summary.map((x) => [x.product, x.avg_risk_score]), 0.85, 1.75, 6.6, 3.1, C.gold);
  note(s, "Recommendation", "Use transcript intelligence as a product risk router: extract the affected product, evidence quote, account, sentiment, and action owner. Detect should be the first executive dashboard surface because outages, SIEM connectors, alert quality, and competitive gaps recur across call types.", 8.0, 1.85, 3.8, 2.7);
  footer(s);
}

// Slide 7
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "Highest-risk meetings show the decisions leaders should force");
  const headers = [["Meeting", 0.72, 5.2], ["Theme", 6.15, 2.0], ["Risk", 8.35, 0.8], ["Leadership question", 9.35, 2.8]];
  headers.forEach(([t, x, w]) => s.addText(t, { x, y: 1.62, w, h: 0.25, fontSize: 10, bold: true, color: C.muted, margin: 0 }));
  summary.highest_risk_meetings.slice(0, 6).forEach((item, i) => {
    const y = 1.95 + i * 0.72;
    rect(s, 0.65, y, 11.7, 0.55, C.white, C.line);
    s.addText(item.title.slice(0, 62), { x: 0.82, y: y + 0.15, w: 5.0, h: 0.2, fontSize: 9.5, color: C.ink, margin: 0, fit: "shrink" });
    s.addText(item.theme, { x: 6.15, y: y + 0.15, w: 1.9, h: 0.2, fontSize: 9.5, color: C.ink, margin: 0, fit: "shrink" });
    s.addText(String(item.risk_score), { x: 8.45, y: y + 0.15, w: 0.4, h: 0.2, fontSize: 11, bold: true, color: C.red, margin: 0 });
    s.addText("Owner, tradeoff, customer impact", { x: 9.35, y: y + 0.15, w: 2.7, h: 0.2, fontSize: 9.5, color: C.ink, margin: 0, fit: "shrink" });
  });
  footer(s);
}

// Slide 8
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "A lightweight clustering experiment validates and challenges the taxonomy");
  barChart(s, clusterSummary.map((x) => [`C${x.cluster_id}: ${x.cluster_label}`, x.meetings]), 0.75, 1.65, 6.9, 4.3, C.green);
  note(s, "What the experiment adds", "The pipeline includes a dependency-free TF-IDF k-means pass. It is not the production classifier; it is a discovery check that groups similar meetings and compares each cluster with the hand-labeled business theme. The result gives reviewers evidence that the taxonomy was tested, not only asserted.", 8.15, 1.75, 3.8, 2.9);
  footer(s);
}

// Slide 9
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "The AI layer includes retrieval, confidence, and human review");
  card(s, "Theme confidence", `${Math.round(evaluation.avg_theme_confidence * 100)}%`, "Average confidence across the rule-labeled taxonomy.", 0.75, 1.65, C.teal);
  card(s, "Cluster purity", `${Math.round(evaluation.avg_cluster_purity * 100)}%`, "How often unsupervised clusters align with dominant business labels.", 4.85, 1.65, C.green);
  card(s, "Review queue", String(evaluation.low_confidence_meetings), "Low-confidence meetings routed for human review before automation.", 8.95, 1.65, C.gold);
  note(s, "Production AI path", "The current repo uses dependency-free TF-IDF retrieval as a RAG-style prototype. In production, I would replace this with embedding search, LLM extraction constrained to retrieved transcript evidence, confidence thresholds, and human review for ambiguous or high-risk account conversations.", 1.0, 3.55, 10.9, 2.0);
  footer(s);
}

// Slide 10
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "A gold-label harness turns this from analysis into an AI system");
  card(s, "Call type", `${Math.round(goldEvaluation.call_type_accuracy * 100)}%`, "Accuracy on the curated validation slice.", 0.75, 1.65, C.teal);
  card(s, "Theme", `${Math.round(goldEvaluation.theme_accuracy * 100)}%`, "Accuracy on primary business taxonomy labels.", 4.85, 1.65, C.green);
  card(s, "Risk F1", `${Math.round(goldEvaluation.high_risk_detection.f1 * 100)}%`, "High-risk detection precision/recall balance.", 8.95, 1.65, C.gold);
  note(s, "Why this matters", "A senior AI system should not stop at generated charts. The repo now includes a 20-meeting gold-label sample and reports accuracy plus precision/recall/F1. In production, this expands into a stratified validation set, reviewer agreement, regression tests, and drift monitoring.", 1.0, 3.55, 10.9, 2.0);
  footer(s);
}

// Slide 11
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "Production extensions: real embeddings, API service, and tests");
  card(s, "Embeddings", "OpenAI", "Optional real retrieval via text-embedding-3-small when OPENAI_API_KEY is set.", 0.75, 1.65, C.teal);
  card(s, "API", "FastAPI", "Review endpoints for summary, meetings, retrieval examples, and human-review queue.", 4.85, 1.65, C.green);
  card(s, "Tests", "6", "Unit coverage for classifier, routing, gold eval, and vector similarity behavior.", 8.95, 1.65, C.gold);
  note(s, "Why this matters", "The repo remains easy to run locally, but the architecture now has clear production interfaces: swap TF-IDF retrieval for embeddings, expose review workflows through an API, and protect behavior with tests and gold-label regression checks.", 1.0, 3.55, 10.9, 2.0);
  footer(s);
}

// Slide 12
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "Three insight products would make this valuable beyond analysis");
  card(s, "Sales / CS", "1", "Revenue risk heatmap: renewal language + competitor mentions + negative sentiment.", 0.75, 1.8, C.teal);
  card(s, "Product", "2", "Product gap backlog: repeated pain points with quotes, accounts, and urgency.", 4.85, 1.8, C.gold);
  card(s, "Engineering", "3", "Incident learning loop: connect support pain to post-incident and sprint-planning follow-through.", 8.95, 1.8, C.green);
  s.addText("These are stakeholder workflows, not charts. The product should help each leader decide what to do next and where to look for evidence.", {
    x: 1.0,
    y: 4.2,
    w: 10.8,
    h: 0.9,
    fontSize: 22,
    bold: true,
    color: C.ink,
    align: "center",
    margin: 0,
    fit: "shrink",
  });
  footer(s);
}

// Slide 13
{
  const s = pptx.addSlide();
  addBg(s);
  title(s, "Recommended next build");
  bullets(s, [
    "Ship a theme and risk dashboard for Detect reliability first.",
    "Add account-level revenue risk overlays for renewal and competitive calls.",
    "Add owner extraction so action items become trackable workflow, not static notes.",
    "Upgrade classifier with embeddings or LLM labels, keeping the rule layer as explainable QA.",
  ], 0.9, 1.85, 6.4, 2.4, 18);
  rect(s, 8.0, 1.8, 3.6, 3.4, C.white, C.line);
  s.addText("Demo path", { x: 8.35, y: 2.1, w: 2.2, h: 0.3, fontSize: 18, bold: true, color: C.ink, margin: 0 });
  s.addText("1. Run src/analyze_transcripts.py\n2. Open outputs/dashboard.html\n3. Review analysis_report.md\n4. Walk through this deck\n5. Show highest-risk CSV rows", {
    x: 8.35,
    y: 2.65,
    w: 2.8,
    h: 1.7,
    fontSize: 15,
    color: C.ink,
    margin: 0,
    fit: "shrink",
  });
  footer(s);
}

pptx.writeFile({ fileName: path.join(deliverablesDir, "Transcript_Intelligence_Leadership_Deck.pptx") });
